AWSTemplateFormatVersion: "2010-09-09"
Description: Create stack for demo lambda MQ counsumer

Parameters:
  DeploymentBucket:
    Type: String
  DeploymentKey:
    Type: String
  SecurityGroup:
    Type: String
  Subnet:
    Type: String

Resources:
  SampleLambdaMqConsumer:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: !Ref DeploymentBucket
        S3Key: !Ref DeploymentKey
      Description: Sample Lambda MQ Consumer
      FunctionName: MqAwsSampleLambdaConsumer
      Handler: com.steinschreiber.aws.samples.SampleMySqlMessageProcessor::handler
      Environment:
        Variables:
          "MQMYSQLSAMPLE_DBUSER": "developer"
          "MQMYSQLSAMPLE_DBPASSWORD": "developer"
          "MQMYSQLSAMPLE_DBNAME": "awsmqsample"
          "MQMYSQLSAMPLE_DBHOST": "testmariadb.c9rcnbof579v.us-west-2.rds.amazonaws.com"
          "MQLAMBDA_HOST": "ec2-35-162-54-98.us-west-2.compute.amazonaws.com"
          "MQLAMBDA_CHANNEL": "PASS.SVRCONN"
          "MQLAMBDA_USERID": "demo"
          "MQLAMBDA_PASSWORD": "demo"
      MemorySize: 256
      Role: "arn:aws:iam::473870623194:role/lambda_vpc_execution"
      Runtime: java8
      Timeout: 10
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroup
        SubnetIds:
          - !Ref Subnet
